[mongoDB]
dataSource = "mongodb://localhost:27017"
db = "mongo-to-elastic"

[elastic]
uri ="http://localhost:9200/"
user ="hojin"
password ="testHojin"

[collections]
[collections.collectionOne]
name ="collectionOne"

[collections.collectionTwo]
name ="collectionTwo"
